public class {{api_name}} {

    public void onBeforeInsert(List<{{object_name}}> records) {

    }

    public void onAfterInsert(List<{{object_name}}> records) {

    }

    public void onBeforeUpdate(List<{{object_name}}> records,
            Map<Id,{{object_name}}> oldMap) {

    }

    public void onAfterUpdate(List<{{object_name}}> records,
            Map<Id,{{object_name}}> oldMap) {

    }

    public void onBeforeDelete(List<{{object_name}}> records) {

    }

    public void onAfterDelete(List<{{object_name}}> records) {

    }

    public void onAfterUndelete(List<{{object_name}}> records) {

    }




}